### ISSUE TITLE
build block with proof of inclusion

### ISSUE THREAD

**Issue by zsluedem** [lu-bann/rbuilder#4]
Based on https://dear-twist-ac1.notion.site/Preconfirmations-API-Specification-1363b4619cb080a6a4cfd170c61771bc

For preconfs, the builder need to submit the header with proof to the relay . We need to updata that part.

**Comment by da-bao-jian** [comment]
Is this being implemented on the builder or sidecar? 

I saw that the sidecar should verify the proof on its side as well: with this API method GET /header_with_proofs

See: https://dear-twist-ac1.notion.site/Preconfirmations-API-Specification-1363b4619cb080a6a4cfd170c61771bc

**Comment by zsluedem** [comment]
![image](https://github.com/user-attachments/assets/c61a3f83-dc99-426a-a9fd-e36467c4813e)
The green line. Submit block with proof. So it happened on the builder side.

**Comment by zsluedem** [comment]
close it because I created two detail issues #5 #6
